### ISSUE TITLE
No LoginModule found for org.apache.kafka.common.security.scram.ScramLoginModule

### ISSUE THREAD

**Issue by elebeaup** [streamthoughts/jikkou#273]
**Describe the bug**
SASL/SCRAM authentication doesn't work via native binary

**To Reproduce**
Use a configuration like this that specifies the sasl mechanism:
```
{
  "currentContext" : "localhost",
  "localhost" : {
    "configFile" : null,
    "configProps" : {
      "kafka.client.sasl.mechanism" : "SCRAM-SHA-512",
      "kafka.client.sasl.jaas.config" : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"****\" password=\"****\";",
      "kafka.client.security.protocol" : "SASL_PLAINTEXT",
      "kafka.client.bootstrap.servers" : "BOOTSTRAPSERVERS"
    }
  }
}
```

and try to run this command :
```
jikkou get kb
```

**Expected behavior**
Jikkou should run normally without errors.

**Screenshots/Configs**
Stacktrace
```
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:488)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:134)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at io.streamthoughts.jikkou.kafka.internals.KafkaUtils.newAdminClient(KafkaUtils.java:37)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.lambda$new$0(AdminClientContext.java:110)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.client(AdminClientContext.java:215)
	at io.streamthoughts.jikkou.kafka.AdminClientContext.invoke(AdminClientContext.java:155)
	at io.streamthoughts.jikkou.kafka.control.AdminClientKafkaBrokerCollector.listAll(AdminClientKafkaBrokerCollector.java:95)
	at io.streamthoughts.jikkou.api.DefaultApi.getResources(DefaultApi.java:287)
	at io.streamthoughts.jikkou.client.command.get.GetResourceCommand.call(GetResourceCommand.java:77)
	at io.streamthoughts.jikkou.client.command.get.GetResourceCommand.call(GetResourceCommand.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at io.streamthoughts.jikkou.client.Jikkou$1.execute(Jikkou.java:153)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.streamthoughts.jikkou.client.Jikkou.execute(Jikkou.java:136)
	at io.streamthoughts.jikkou.client.Jikkou.main(Jikkou.java:119)
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: No LoginModule found for org.apache.kafka.common.security.scram.ScramLoginModule
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:522)
	... 22 more
Caused by: javax.security.auth.login.LoginException: No LoginModule found for org.apache.kafka.common.security.scram.ScramLoginModule
	at java.base@17.0.8/javax.security.auth.login.LoginContext.invoke(LoginContext.java:739)
	at java.base@17.0.8/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
	at java.base@17.0.8/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
	at java.base@17.0.8/java.security.AccessController.executePrivileged(AccessController.java:144)
	at java.base@17.0.8/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base@17.0.8/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
	at java.base@17.0.8/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:170)
	... 26 more
```

**Runtime environment**
- OS: Ubuntu
- Jikkou: 0.28.0-early-access
- Docker version 24.0.6, build ed223bc]
 - Kafka Cluster Version: 6.0.9-ce

**Additional context**
This works fine via fatjar.

**Comment by fhussonnois** [comment]
Hi @elebeaup thank you very much for opening this issue. The issue is resolved,you should be able to test it using the [early-access release](https://github.com/streamthoughts/jikkou/releases/tag/0.28.0-early-access) as soon as the CI/CD built it.

**Comment by mperello-tech** [comment]
Hello @fhussonnois , I have tried the [early access release](https://github.com/streamthoughts/jikkou/releases/tag/0.28.0-early-access) but i still get the same error as reported here. Is there anything additional needed aside from what was posted as configuration by @elebeaup ?
